name: TEST TAG

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      BUILD_VERSION:
        description: 'Build version'
        default: '1.0-SNAPSHOT'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref }}"
  print:
    #if: ${{ github.ref == 'refs/heads/master' }}
    needs: on-main-branch-check
    runs-on: ubuntu-latest
    steps:
      - name: Print text
        run: |
            echo "Is main = ${{ needs.on-main-branch-check.outputs.on_main }}"
  # This workflow contains a single job called "build"
#  print:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      - uses: actions-ecosystem/action-regex-match@v2
#        id: version
#        with:
#          text: ${{  github.ref_name }}
#          regex: '^v(.*)$'
#          flags: gm
#      - name: Set env
#        run: |
#              echo BUILD_VERSION=$BUILD_VERSION
#        env:
#          BUILD_VERSION: ${{ steps.version.outputs.group1 }}
#      - name: GitHub Tag Name example
#        run: |
#            echo "Version frim env: $BUILD_VERSION"
#            echo "Version: ${{ steps.version.outputs.match }}"
#            echo "Version: ${{ steps.version.outputs.group1 }}"
#            echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
#            echo "Tag name from github.ref_name: ${{  github.ref_name }}"
