name: TEST ACTION 2

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    # Steps represent a sequence of tasks that will be executed as part of the job
  read:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: .github/workflows/action.yml
        with:
          value: TEST VALUE
