name: TEST TAG

on:
  push:
    tags:
      - 'v**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: version
        with:
          text: $GITHUB_REF_NAME
          regex: '^.*$'
          flags: gm
      - name: GitHub Tag Name example
        run: |
            echo "Version: ${{ steps.version.outputs.match }}"
            echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
            echo "Tag name from github.ref_name: ${{  github.ref_name }}"
