name: TEST ACTION 2

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    # Steps represent a sequence of tasks that will be executed as part of the job
  read:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the tag version
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ozonophore/dd
          prefix: v
      - run: |
           echo "Tag version: ${{ steps.tag_version.outputs.tag }}"  
      - name: Parse semver string
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: '${{ steps.tag_version.outputs.tag }}'
          version_extractor_regex: '^v(.*)$'
      - name: Use parsed semver
        run: |
            echo "v${{ steps.semver_parser.outputs.major }}"
            echo "v${{ steps.semver_parser.outputs.minor }}"
            echo "v${{ steps.semver_parser.outputs.patch }}"
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
      - name: Give permission
        run: chmod 777 math-homework.txt
      - name: Display structure of downloaded files
        run: ls -la
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
