name: TEST ACTION

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      some_variable:
        description: 'Some text'
        default: 'Text'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Prod
    env:
      TEST_VALUE: ${{ github.event.inputs.some_variable }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print test
        run: echo $TEST_VALUE
