name: TEST ACTION 2

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    # Steps represent a sequence of tasks that will be executed as part of the job
  read:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the tag version
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ozonophore/dd
          prefix: v
      - run: |
           echo "Tag version: ${{ steps.tag_version.outputs.tag }}"  
      - uses: actions-ecosystem/action-regex-match@v2
        id: version_major
        name: Prepare a version from a tag
        with:
          text: ${{ steps.tag_version.outputs.tag }}
          regex: '^v([0-9]+)\.(.*)'
          flags: gm
      - uses: actions-ecosystem/action-regex-match@v2
        id: version
        name: Prepare a version from a tag
        with:
          text: ${{ steps.version.outputs.group2 }}
          regex: '^([0-9]+)\.(.*)'
          flags: gm
      - run: |
          echo "MAJOR: ${{ steps.version_major.outputs.group1 }}"
          echo "MINOR: ${{ steps.version_minor.outputs.group1 }}"
          echo "PATCH: ${{ steps.version_minor.outputs.group2 }}"
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
      - name: Give permission
        run: chmod 777 math-homework.txt
      - name: Display structure of downloaded files
        run: ls -la
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
