name: TEST ACTION

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      some_variable:
        description: 'Some text'
        default: 'Text'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Prod
    env:
      TEST_VALUE: ${{ github.event.inputs.some_variable }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print test
        run: echo $TEST_VALUE
      - shell: bash
        name: Create a file
        run: |
          echo $TEST_VALUE > math-homework.txt
      - shell: bash
        name: Give permission
        run: |
          chmod 777 math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
  read:
    name: Display results
    runs-on: ubuntu-latest
    needs: print
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Give permission
        run: chmod 777 math-homework.txt
      - name: Display structure of downloaded files
        run: ls -la
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value